### ISSUE TITLE
ObservableAgent - Auctioneer missing information

### ISSUE THREAD

**Issue by villgust** [flexiblepower/powermatcher#108]
The Auctioneer does not use it's agentId when reporting events.
The Auctioneer does not report the aggregated bid in the csvlogging

**Comment by marcdejonge** [comment]
Please check if this works in the new version

**Comment by marcdejonge** [comment]
I think this bug (if it still exists) should be fixed before the release.

**Comment by marcdejonge** [comment]
There is a new AggregatedBidEvent that is put out by the Auctioneer and Concentrator that should be used. The CSVLogger does not write them yet in any way.
