### ISSUE TITLE
Java version compliance - only Java 7+

### ISSUE THREAD

**Issue by jbwan** [flexiblepower/powermatcher#141]
There appears to be an issue with the current development branch and compatibility with Java 1.5 as indicated in the Wiki at https://github.com/flexiblepower/powermatcher/wiki/SettingUpTheIDE#installing-the-java-development-kit 

For example, in CSVLogger.java under the net.powermatcher.core.monitoring package, PrintWriter is used in the method writeLineToCSV(String[] line, File outputFile) but it raises a compilation error that PrintWriter does not implement java.lang.AutoClosable which was only introduced as an implemented interface for PrintWriter in Java 7.

**Comment by marcdejonge** [comment]
We switched the project back to Java 1.6, just like the rest of the flexiblepower projects.
