### ISSUE TITLE
Powermatcher in Islanded Microgrid, Include Prognosis Data

### ISSUE THREAD

**Issue by JasperNR** [flexiblepower/powermatcher#219]
I am currently researching on a self-regulating grid based on smart contracts (blockchain technology). I have read through the PowerMatcher documentation and the system seems to be really promising and well documented.

I was wondering about two points though:
1) On your website you state: "By means of the PowerMatcher a microgrid can be created that maintains its own balance." I couldn't find anything about this in the documentation. Have you already implemented a grid that has been balanced by the PowerMatcher instead of an external party (e.g. a TSO)?
2) The PowerMatcher seems to be a perfect system for continous and real-time power balancing. Do you plan on or have you implemented any solutions for the prognosis of power generation/consumption (e.g. include weather prognosis)? Or will this solely be done locally  on the level of the device agents?

Looking forward to hear from you!

**Comment by wilcowijbrandi** [comment]
Hi Jasper,

Thanks for getting in touch with us! To answer your questions:
1. Balancing a microgrid is one application for PowerMatcher (actually, balancing is what PowerMatcher does by default). However, in most pilots, we use a different use case: we add an ObjectiveAgent to the cluster, which influences the cluster to achieve another goal than balancing. Typical examples are trading on a day-ahead power market, performing congestion management on the power grid or reacting on imbalance prices. Also strategies for households have been implemented (e.g. try to consume energy locally produced by PV panels first).
2. As you very correctly point out PowerMatcher is very good for continuous and real-time control. However, for some use cases this you might want to look at the future. This is typically implemented in another piece of software (which could use forecasting techniques), which then influences the cluster using an ObjectiveAgent. So typically we use other software to create a plan for the cluster, and then use PowerMatcher to execute the plan. The advantage of this approach is that PowerMatcher can execute the plan in more detail and can compensate for forecast errors and unforeseen events. This approach has also been done in several pilot projects.

I hope this helps a bit. If you are interested, you can contact me through wilco.wijbrandi@tno.nl and we could discuss this in a bit more detail.

Best regards,
Wilco
