### ISSUE TITLE
Make the concentrator and auctioneer more event-driver

### ISSUE THREAD

**Issue by christiaan-bosch** [flexiblepower/powermatcher#46]
The concentrator should have a minimum and maximum time between update cycles. When it receives a bid-update from one of the agents before the minimum time has passed, the concenttrator will wait with sending the aggregated bid update. Also, when it doesn't receive a bid update for more than the maximum time, it will still send a bid update to its parent matcher.

**Comment by marcdejonge** [comment]
Before we will add this functionality, @wilcowijbrandi and I will think if this really should be the solution. This is a nice-to-have for the next release.

**Comment by marcdejonge** [comment]
Fixed
