### ISSUE TITLE
PM Quick Start package

### ISSUE THREAD

**Issue by bjornamkreutz** [flexiblepower/powermatcher#52]
Who is the intended audience?
- Developers

What is the intention of this package?
- Developer guidance and introduction to powermatcher
- Should tell a story and provide guidance into the various aspects of Powermatcher

Location:
- Wiki

Contents:
- Chapter Highlevel PM architecture introduction
- Chapter about getting started:
 - Working development environment (reuse from FPAI manual)
 - Eclipse
 - Guide on how to use OSGI launcher
 - Indicate the use from Repositories
- Chapter How to get code from GitHub, (Working with GitHub and how to contribute is out of scope)
- Chapter how to start an actioneer and hello world agent
- Chapter to build up a cluster
 - Local / Cloud
 - Remote (FPAI)?
 - Distributed Local & Remote (Messagebus)
 - Add concentrator
 - Add multiple device agents (for aggregation)
- Chapter about heatpump device agent creation
 - Buildup an agent
 - Use with simulator (should be simple)
 - Refer to FPAI as alternative to develop an agent
- Chapter about objective agent creation in the form of a programming assignment
 - How to create an agent
 - How to influence the cluster via objective agent
 - Follow windfarm algoritm
- Chapter over messagebus (optional)

- Include link to powermatcher website and powermatcher youtube video.
![whiteboard](https://cloud.githubusercontent.com/assets/653038/4826343/5cca1258-5f6f-11e4-936c-e565432ab03e.jpg)

**Comment by marcdejonge** [comment]
A demonstration for the PowerMatcher will be combined with the FPAI demonstration in the next release
